matrix:
  GO_VERSION:
    - "1.10"
  GOOS:
    - "windows"
    - "linux"
    - "darwin"
  GOARCH:
    - "amd64"
pipeline:
  build:
    image: golang:${GO_VERSION}-alpine
    environment:
      - FILENAME=${DRONE_REPO_NAME}-${GOOS}-${GOARCH}
    commands:
      - go build -ldflags "-s -w" -o "${FILENAME/windows-amd64/windows-amd64.exe}"
  release:
    image: plugins/github-release
    secrets: [ github_token ]
    environment:
      - FILENAME=${DRONE_REPO_NAME}-${GOOS}-${GOARCH}
    files: [ "${FILENAME}" ]
    when:
      event: tag
