kind: pipeline
name: default

steps:
- name: build
  image: golang:1.11
  pull: true
  environment:
  - CGO_ENABLED=0
  - GOOS=linux
  - GOARCH=amd64
  commands:
  - export FILENAME=${DRONE_REPO_NAME}-${GOOS}-${GOARCH}
  - if [ "$GOOS" = "windows" ]; then export FILENAME=$FILENAME.exe; fi
  - go build -ldflags "-s -w" -o dist/$FILENAME
- name: release
  image: plugins/github-release
  settings:
    files:
    - dist/*
    api_key:
      from_secret: github_token
  when:
    event: tag
