matrix:
  GO_VERSION:
    - "1.10"
  GOOS:
    - linux
    - windows
    - darwin
  GOARCH:
    - amd64
    - arm64
pipeline:
  build:
    image: golang:${GO_VERSION}-alpine
    pull: true
    commands:
      - export FILENAME=${DRONE_REPO_NAME}-${GOOS}-${GOARCH}
      - go build -ldflags "-s -w" -o dist/$FILENAME
  release:
    image: plugins/github-release
    secrets: [ github_token ]
    files:
      - dist/*
    when:
      event: tag
